### ISSUE TITLE
我k8s中部署greeter中的srv,出错了，不懂哪里的问题啊

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#24]
[root@k8s-deploy micro-k8s-test]# kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
greeter-66659f774c-v4jkl   1/1     Running   0          4s
[root@k8s-deploy micro-k8s-test]# docker logs greeter-66659f774c-v4jkl
Error: No such container: greeter-66659f774c-v4jkl
[root@k8s-deploy micro-k8s-test]# kubectl logs greeter-66659f774c-v4jkl
2019/06/04 15:38:03 Listening on [::]:8080
2019/06/04 15:38:03 Broker Listening on [::]:10001
2019/06/04 15:38:03 Broker [grpc] Listening on [::]:10001
2019/06/04 15:38:03 Registering node: micro.greeter-f8c284a2-9921-4799-9abd-6422fa1a8f21
2019/06/04 15:38:03 K8s: request failed with code 403
2019/06/04 15:38:03 K8s: request failed with body:
2019/06/04 15:38:03 {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"greeter-66659f774c-v4jkl\" is forbidden: User \"system:serviceaccount:default:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"name":"greeter-66659f774c-v4jkl","kind":"pods"},"code":403}

**Comment by printfcoder** [comment]
看上去是你没有配好权限组，查下相关资料吧，这和micro没关系。"system:serviceaccount:default:default"是k8s给pod绑定用的默认用户，你需要给这个用户加上权限。

**Comment by watermelon-brother** [comment]
@printfcoder 这个我加上权限后确实可以了

**Comment by watermelon-brother** [comment]
@printfcoder greeter-web 调用 greeter-srv 出现500错误 ，帮忙看看啊，[问题地址](https://github.com/micro/examples/issues/65)

**Comment by k1ng440** [comment]
this is what i use
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coinreadservice.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "coinreadservice.name" . }}
    helm.sh/chart: {{ include "coinreadservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "coinreadservice.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "coinreadservice.name" . }}
    helm.sh/chart: {{ include "coinreadservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - list
    - patch
    - watch

- apiGroups:
    - ""
  resources:
    - configmaps
  resourceNames:
    - {{ include "coinreadservice.name" . }}
    - {{ template "coinreadservice.serviceAccountName" . }}
  verbs:
    - list
    - patch
    - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "coinreadservice.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "coinreadservice.name" . }}
    helm.sh/chart: {{ include "coinreadservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "coinreadservice.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "coinreadservice.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
```
