### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by watermelon-brother** [micro-in-cn/tutorials#26]
# error message
```json
{
    "id": "go.micro.client",
    "code": 500,
    "detail": "error selecting greeter node: not found",
    "status": "Internal Server Error"
}
```

# greeter-web
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	hello "github.com/micro/examples/greeter/srv/proto/hello"
	"github.com/micro/go-micro/client"
	"github.com/micro/go-web"
	k8s "github.com/micro/kubernetes/go/web"

	"context"
)

func main() {
	service := k8s.NewService(
		web.Name("go.micro.web.greeter"),
	)

	service.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "POST" {
			r.ParseForm()

			name := r.Form.Get("name")
			if len(name) == 0 {
				name = "World"
			}

			cl := hello.NewSayService("greeter", client.DefaultClient)
			rsp, err := cl.Hello(context.Background(), &hello.Request{
				Name: name,
			})

			if err != nil {
				http.Error(w, err.Error(), 500)
				return
			}

			w.Write([]byte(`<html><body><h1>` + rsp.Msg + `</h1></body></html>`))
			return
		}

		fmt.Fprint(w, `<html><body><h1>Enter Name<h1><form method=post><input name=name type=text /></form></body></html>`)
	})

	if err := service.Init(); err != nil {
		log.Fatal(err)
	}

	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

# greeter-srv
```go
package main

import (
	"log"
	"time"

	hello "github.com/micro/examples/greeter/srv/proto/hello"
	"github.com/micro/go-micro"
	k8s "github.com/micro/kubernetes/go/micro"
	"context"
)

type Say struct{}

func (s *Say) Hello(ctx context.Context, req *hello.Request, rsp *hello.Response) error {
	log.Print("Received Say.Hello request")
	rsp.Msg = "Hello " + req.Name
	return nil
}

func main() {
	service := k8s.NewService(
		micro.Name("greeter"),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*10),
	)

	// optionally setup command line usage
	service.Init()

	// Register Handlers
	hello.RegisterSayHandler(service.Server(), new(Say))

	// Run server
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```
# greeter-srv service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: greeter
  namespace: micro
  labels:
    app: greeter
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    name: greeter-srv

```
# greater-srv pod
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-srv
  template:
    metadata:
      labels:
        name: greeter-srv
    spec:
      containers:
        - name: greeter
          command: [
            "/greeter-srv",
            "--selector=static",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
          ]
          image: harbor.my.work.com/micro-test/greeter-srv:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: greeter-port
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=greeter",
            "--server_address=0.0.0.0:8080"
          ]
          image: harbor.my.work.com/micro-test/health:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3

```

**Comment by printfcoder** [comment]
查看注册中心是否web和srv两个服务都注册上了

**Comment by printfcoder** [comment]
将client.DefaultClient换成service.Client()

**Comment by watermelon-brother** [comment]
@printfcoder greerer-api 用的是这个，请求后空白，greeter-web不支持service.Client()，[你本地试试我的项目吧](https://github.com/watermelon-brother/micro-k8s-problem)

**Comment by Allenxuxu** [comment]
service.Options().Service.Client()

@watermelon-brother micro.web 用这个client

**Comment by watermelon-brother** [comment]
@Allenxuxu 兄弟厉害啦！这问题我搞了几天，文档没有，问作者也不了我，哎！你这是哪里看到的，读源码吗？我现在greeter-web 已经成功调用 greeter-srv了，但是greeter-api调用greeter-srv返回空白，醉了

**Comment by Allenxuxu** [comment]
@watermelon-brother 😂我之前也遇到过类似的问题。  返回空白啥意思，状态码500?

**Comment by watermelon-brother** [comment]
@Allenxuxu  哥们方便留个联系方式吗
# api网关
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro
  name: micro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-api
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      containers:
      - name: api
        env:
        - name: MICRO_ENABLE_STATS
          value: "true"
        args:
        - api
        - "--handler=api"
        image: harbor.my.work.com/micro-test/micro:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api-port

```
# api 客户端

```go
package main

import (
	"encoding/json"
	"log"
	"strings"

	hello "github.com/micro/examples/greeter/srv/proto/hello"
	"github.com/micro/go-micro"
	"github.com/micro/go-micro/errors"
	api "github.com/micro/micro/api/proto"
	k8s "github.com/micro/kubernetes/go/micro"
	"context"
)

type Say struct {
	Client hello.SayService
}

func (s *Say) Hello(ctx context.Context, req *api.Request, rsp *api.Response) error {
	log.Print("Received Say.Hello API request")

	name, ok := req.Get["name"]
	if !ok || len(name.Values) == 0 {
		return errors.BadRequest("go.micro.api.greeter", "Name cannot be blank")
	}

	response, err := s.Client.Hello(ctx, &hello.Request{
		Name: strings.Join(name.Values, " "),
	})
	if err != nil {
		return err
	}

	rsp.StatusCode = 200
	b, _ := json.Marshal(map[string]string{
		"message": response.Msg,
	})
	rsp.Body = string(b)

	return nil
}

func main() {
	service := k8s.NewService(
		micro.Name("go.micro.api.greeter"),
	)

	// parse command line flags
	service.Init()

	service.Server().Handle(
		service.Server().NewHandler(
			&Say{Client: hello.NewSayService("greeter", service.Client())},
		),
	)

	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}

```
通过API网关调用，返回空白

```yaml
---general----
Request URL: http://192.168.0.220:20004/greeter/say/hello?name=John
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.0.220:20004
Referrer Policy: no-referrer-when-downgrade

-----response------
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sun, 09 Jun 2019 03:48:25 GMT
Content-Length: 0

----request-------------
GET /greeter/say/hello?name=John HTTP/1.1
Host: 192.168.0.220:20004
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
DNT: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
name=John
```
